import './context-menu.css';
export function createContextMenu(onError=()=>{}){
 let node=null,origin=null;
 function close(focus=false){node?.remove();node=null;if(focus&&origin?.isConnected)origin.focus?.({preventScroll:true});}
 document.addEventListener('pointerdown',e=>{if(node&&!node.contains(e.target))close();},true);
 window.addEventListener('blur',()=>close());window.addEventListener('resize',()=>close());document.addEventListener('scroll',()=>close(),true);
 document.addEventListener('keydown',e=>{if(!node)return;if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();close(true);}else if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();e.stopImmediatePropagation();const buttons=[...node.querySelectorAll('button:not(:disabled)')],i=buttons.indexOf(document.activeElement);buttons[e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length]?.focus();}},true);
 return {close,open(event,title,actions){close();origin=event.target;node=document.createElement('div');node.className='editor-context-menu';node.setAttribute('role','menu');node.setAttribute('aria-label',title);const heading=document.createElement('strong');heading.textContent=title;node.append(heading);for(const action of actions){const button=document.createElement('button');button.type='button';button.setAttribute('role','menuitem');button.textContent=action.label;button.disabled=Boolean(action.disabled);button.dataset.contextCommand=action.key;button.addEventListener('click',async e=>{e.stopPropagation();close();try{await action.run();}catch(error){onError(error);}});node.append(button);}document.body.append(node);const rect=node.getBoundingClientRect();node.style.left=Math.max(4,Math.min(event.clientX,innerWidth-rect.width-4))+'px';node.style.top=Math.max(4,Math.min(event.clientY,innerHeight-rect.height-4))+'px';node.querySelector('button:not(:disabled)')?.focus({preventScroll:true});}};
}
