import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {TransformControls} from 'three/addons/controls/TransformControls.js';
import {EnvironmentRuntime} from './environment-runtime.js';
import {addReferencePeople} from './environment-references.js';
import {fitEnvironmentShadow,environmentShadowBounds} from './environment-shadows.js';
import {newId,validateEnvironment,createEnvironment} from './environment-schema.js';
import {selectedRoots,subtreeIds,assignMatrix,reparentNode,groupSelection,ungroupSelection,copySelection,pasteSelection,validateEnvironmentLibrary} from './environment-operations.js';
import './environment-editor.css';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(text,act,title='')=>`<button data-act="${act}" title="${esc(title||text)}">${text}</button>`;
let env,environments=[],assets=[],library={folders:[],assignments:{}},projectId='',baseRevision=0,selected=new Set(),primary='',clipboard=[],assetSelection=new Set(),folder='',collapsed=new Set(),undo=[],redo=[],dirty=false,busy=false;
let referenceSettings={},referenceMultiple=false;const pending=new Map(),importedIds=new Set();let counter=0;
$('#app').innerHTML=`<main class="workspace"><section class="work-area"><header><div class="toolbar">${btn('撤销','undo','Ctrl+Z')}${btn('重做','redo','Ctrl+Shift+Z')}${btn('导入 ▾','import-menu')}${btn('删除','delete','X / Delete')}${btn('复制','copy','Ctrl+C')}${btn('粘贴','paste','Ctrl+V')}${btn('当前镜头作为游戏镜头','camera')}${btn('查看游戏镜头','game-camera','小键盘 0')}</div><div class="view-tools">${btn('移动','translate','G')}${btn('旋转','rotate','R')}${btn('缩放','scale','S')}${btn('框选','box-select','B')}${btn('镜头回到人物前','focus-people')}<label><input id="show-references" type="checkbox" checked>参考人物</label><label><input id="show-grid" type="checkbox" checked>网格</label>${btn('快捷键','help')}<span id="status">正在打开…</span></div></header><div id="viewport" tabindex="0"><div id="selection-box" hidden></div><small id="view-caption">16:9 · 中键旋转 / Shift＋中键平移 / 滚轮缩放</small></div><section class="asset-library"><div class="library-toolbar"><b>场景素材</b><button data-folder="">全部素材</button><span id="breadcrumb"></span>${btn('＋ 文件夹','new-folder')}<label>移入<select id="asset-move"></select></label><small>双击或拖入场景</small></div><div id="assets"></div></section><footer>Shift / Ctrl 多选 · G 移动 · R 旋转 · S 缩放 · X / Y / Z 限定方向 · Enter 确认 · Esc 取消</footer></section><aside class="scene-panel"><div class="environment-bar">${btn('打开一个环境','open-environment','Ctrl+O')}${btn('＋ 新建','new-environment','Ctrl+N')}${btn('保存','save','Ctrl+S')}</div><div class="environment-title">${btn('最近','recent-environments')}<input id="environment-name" data-env="name" maxlength="200" aria-label="当前环境名称"><span id="saved-state"></span></div><div class="scene-body"><div class="scene-content"><section class="outliner"><div class="section-title"><b>场景中的物品</b><span id="selection-count"></span></div><div id="nodes"></div></section><section id="properties"></section></div><nav class="tool-rail">${btn('创建分组','group','Ctrl+G')}${btn('拆开分组','ungroup','Ctrl+Alt+G')}${btn('创建地面','add-ground')}${btn('落到地面','ground')}<label class="snap-switch"><input id="snap" type="checkbox" checked>吸附</label>${btn('创建灯光','add-light')}${btn('创建天空球','add-sky')}${btn('聚焦所选','focus-selected','小键盘 .')}${btn('显示全景','frame-all','Home')}</nav></div></aside></main><div id="dialog-root"></div>`;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(32,16/9,.1,300),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;$('#viewport').prepend(renderer.domElement);
const orbit=new OrbitControls(camera,renderer.domElement);orbit.mouseButtons={LEFT:null,MIDDLE:THREE.MOUSE.ROTATE,RIGHT:THREE.MOUSE.PAN};
scene.add(new THREE.HemisphereLight(0xffffff,0x7181a2,2));const sun=new THREE.DirectionalLight(0xffffff,2.2);scene.add(sun,sun.target);
const references=new THREE.Group(),grid=new THREE.GridHelper(80,160),pivot=new THREE.Group();scene.add(references,grid,pivot);
const runtime=new EnvironmentRuntime(scene),gizmo=new TransformControls(camera,renderer.domElement);scene.add(gizmo.getHelper());let lightHelpers=[],drag=null,modal=null,boxMode=false,boxStart=null,lastPointer=new THREE.Vector2();
const base=(kind,name)=>({id:newId(),kind,name,parentId:null,position:[0,0,0],rotation:[0,0,0],scale:[1,1,1],visible:true});
const assetUrl=a=>`https://project.galgame/${a.path.split('/').map(encodeURIComponent).join('/')}`;
function status(t){$('#status').textContent=t;$('#saved-state').textContent=dirty?'● 未保存':'已保存';}
function state(){return JSON.stringify({environment:env,library});}function restore(s){const v=JSON.parse(s);env=v.environment;library=v.library;const i=environments.findIndex(e=>e.id===env.id);if(i>=0)environments[i]=env;}
function checkpoint(before){if(before===state())return;undo.push(before);if(undo.length>60)undo.shift();redo=[];dirty=true;}
function send(action,payload={}){return new Promise((resolve,reject)=>{const id=String(++counter);pending.set(id,{resolve,reject});window.chrome.webview.postMessage({id,action,payload});});}
window.chrome.webview.addEventListener('message',async e=>{const data=e.data;if(data.environmentRefresh){try{if(busy||modal)throw Error('请先完成当前操作');const init=data.environmentRefresh;for(const item of init.environments||[])if(!environments.some(x=>x.id===item.id))environments.push(item);for(const item of init.assets||[])if(!assets.some(x=>x.id===item.id))assets.push(item);await switchEnvironment(init.environment.id);referenceSettings=init.referenceSettings||{};referenceMultiple=Boolean(init.referenceMultiple);addReferencePeople(references,referenceSettings,referenceMultiple);renderPanels();}catch(error){status(error.message);}return;}const p=pending.get(data.id);if(p){pending.delete(data.id);data.ok?p.resolve(data.data):p.reject(Error(data.error));}});
function roots(){return selectedRoots(env,[...selected]).filter(n=>n.kind!=='sky');}
function attach(){gizmo.detach();const items=roots();if(items.length===1)gizmo.attach(runtime.objects.get(items[0].id));else if(items.length>1){const bounds=new THREE.Box3();for(const n of items)bounds.union(new THREE.Box3().setFromObject(runtime.objects.get(n.id)));if(bounds.isEmpty())for(const n of items)bounds.expandByPoint(runtime.objects.get(n.id).getWorldPosition(new THREE.Vector3()));pivot.position.copy(bounds.getCenter(new THREE.Vector3()));pivot.quaternion.identity();pivot.scale.setScalar(1);pivot.updateMatrixWorld(true);gizmo.attach(pivot);}}
function select(ids){selected=new Set(ids.filter(id=>runtime.objects.has(id)));primary=[...selected].at(-1)||'';attach();renderPanels();}
async function rebuild(){const previous=busy;busy=true;gizmo.detach();try{await runtime.load(env,assets);scene.background=new THREE.Color(env.background);sun.color.set(env.lighting.color);sun.intensity=env.lighting.intensity;const bounds=environmentShadowBounds(runtime.root);bounds.union(new THREE.Box3().setFromObject(references));fitEnvironmentShadow(sun,bounds);for(const h of lightHelpers){scene.remove(h);h.dispose();}lightHelpers=[];runtime.root.traverse(o=>{if(o.isPointLight){const h=new THREE.PointLightHelper(o,.15);scene.add(h);lightHelpers.push(h);}});selected=new Set([...selected].filter(id=>runtime.objects.has(id)));primary=selected.has(primary)?primary:[...selected].at(-1)||'';attach();renderPanels();}finally{busy=previous;}}
async function mutate(callback){const before=state(),previous=[...selected];try{callback();validateEnvironment(env,assets);validateEnvironmentLibrary(library,assets);checkpoint(before);await rebuild();status('有未保存修改');}catch(error){restore(before);selected=new Set(previous);await rebuild();throw error;}}
function renderPanels(){if(!env)return;$('#environment-name').value=env.name;$('#selection-count').textContent=`已选 ${selected.size} 件`;$('#saved-state').textContent=dirty?'● 未保存':'已保存';const icons={group:'▾',model:'▣',imagePlane:'▧',ground:'▱',light:'☀',sky:'◉'},rows=[];function branch(parent,depth){for(const n of env.nodes.filter(x=>(x.parentId||null)===parent)){rows.push(`<div class="node-row ${selected.has(n.id)?'selected':''} ${n.visible===false?'muted':''}" style="padding-left:${depth*14}px"><button class="fold" data-fold="${esc(n.id)}">${n.kind==='group'&&collapsed.has(n.id)?'▸':icons[n.kind]}</button><button class="node-name" data-select="${esc(n.id)}">${esc(n.name)}</button><button class="visibility" data-visible="${esc(n.id)}" title="显示或隐藏">${n.visible===false?'○':'●'}</button></div>`);if(!collapsed.has(n.id))branch(n.id,depth+1);}}branch(null,0);$('#nodes').innerHTML=rows.join('');renderAssets();renderProperties();}
function renderAssets(){const all=assets.filter(a=>['image','sceneModel'].includes(a.type)),folders=library.folders.filter(p=>(p.includes('/')?p.slice(0,p.lastIndexOf('/')):'')===folder);$('#breadcrumb').textContent=folder?'／'+folder:'／工程内全部素材';$('#asset-move').innerHTML=`<option value="">根目录</option>${library.folders.map(f=>`<option value="${esc(f)}">${esc(f)}</option>`).join('')}`;$('#assets').innerHTML=folders.map(f=>`<button class="folder-card" data-folder="${esc(f)}"><span>📁</span>${esc(f.split('/').at(-1))}</button>`).join('')+all.filter(a=>!folder||library.assignments[a.id]===folder).map(a=>`<button draggable="true" class="asset-card ${assetSelection.has(a.id)?'selected':''}" data-asset-select="${esc(a.id)}" title="双击或拖动放入场景">${a.type==='image'?`<img loading="lazy" src="${esc(assetUrl(a))}" alt="">`:'<span class="asset-symbol">▣</span>'}<span class="asset-name">${esc(a.name)}</span><small>${esc(library.assignments[a.id]||'根目录')}</small></button>`).join('');}
function renderProperties(){const n=env.nodes.find(n=>n.id===primary),descendants=n?subtreeIds(env,[n.id]):new Set();$('#properties').innerHTML=`<details ${n?'':'open'}><summary>环境设置</summary><label>天空底色<input data-env="background" type="color" value="${env.background}"></label><label>主灯颜色<input data-light="color" type="color" value="${env.lighting.color}"></label><label>主灯亮度<input data-light="intensity" type="number" min="0" max="10" step=".1" value="${env.lighting.intensity}"></label><small>环境随工程保存，阴影投到实际地面和模型墙壁上。</small></details>${n?`<h3>${selected.size>1?'当前物体（属性只改这一件）':'物体属性'}</h3><label>名称<input data-node="name" type="text" value="${esc(n.name)}" maxlength="200"></label>${n.kind==='sky'?`<label>全景图片<select data-node="assetId"><option value="">纯色天空</option>${assets.filter(a=>a.type==='image').map(a=>`<option value="${esc(a.id)}" ${n.assetId===a.id?'selected':''}>${esc(a.name)}</option>`).join('')}</select></label><label>天空颜色<input data-node="color" type="color" value="${n.color}"></label><small>建议使用 2:1 全景图片。天空球跟随镜头，不投射阴影。</small>`:`<label>所在分组<select data-node="parentId"><option value="">场景根目录</option>${env.nodes.filter(x=>x.kind==='group'&&!descendants.has(x.id)).map(x=>`<option value="${x.id}" ${n.parentId===x.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label>${['position','rotation','scale'].map((key,i)=>`<label class="vector-label">${['位置（米）','旋转（度）','大小'][i]}<div class="vector-inputs">${n[key].map((v,j)=>`<label>${['X','Y','Z'][j]}<input data-vector="${key}" data-index="${j}" type="number" step="${key==='rotation'?1:.1}" value="${key==='rotation'?Math.round(v*180/Math.PI):Number(v.toFixed(3))}"></label>`).join('')}</div></label>`).join('')}`}${n.kind==='light'?`<label>灯光颜色<input data-node="color" type="color" value="${n.color}"></label><label>亮度<input data-node="intensity" type="number" min="0" max="1000" value="${n.intensity}"></label><label>照射范围（米）<input data-node="distance" type="number" min="0" max="10000" value="${n.distance}"></label><label><input data-node="castShadow" type="checkbox" ${n.castShadow?'checked':''}>投射阴影</label>`:''}${n.kind==='ground'?`<label>地面颜色<input data-node="color" type="color" value="${n.color}"></label>`:''}${['ground','imagePlane'].includes(n.kind)?`<label>宽度<input data-node="width" type="number" min=".1" step=".1" value="${n.width}"></label><label>高度<input data-node="height" type="number" min=".1" step=".1" value="${n.height}"></label>`:''}${n.kind==='imagePlane'?`<label><input data-node="unlit" type="checkbox" ${n.unlit?'checked':''}>保持图片原亮度</label><label><input data-alpha type="checkbox" ${n.alphaCutoff?'checked':''}>镂空图片</label>`:''}`:'<p class="empty-hint">选择物体后，这里显示位置和大小。Shift / Ctrl 可多选。</p>'}`;}
async function saveCurrent(){const previous=busy;busy=true;try{validateEnvironment(env,assets);validateEnvironmentLibrary(library,assets);const result=await send('commit',{environment:structuredClone(env),environmentLibrary:structuredClone(library),assets:structuredClone(assets.filter(a=>importedIds.has(a.id))),projectId,baseRevision});baseRevision=result.revision;env.revision=baseRevision;environments[environments.findIndex(x=>x.id===env.id)]=env;dirty=false;importedIds.clear();renderPanels();status('已保存到工程');}finally{busy=previous;}}
function recordRecent(id){try{const key='environment-recent:'+projectId,ids=JSON.parse(localStorage.getItem(key)||'[]');localStorage.setItem(key,JSON.stringify([id,...ids.filter(x=>x!==id)].slice(0,12)));}catch{}}function recentIds(){try{return JSON.parse(localStorage.getItem('environment-recent:'+projectId)||'[]');}catch{return [];}}
function viewGameCamera(){camera.up.set(0,1,0);camera.position.fromArray(env.camera.position);camera.fov=env.camera.fov;camera.updateProjectionMatrix();orbit.target.fromArray(env.camera.target);orbit.update();}
async function switchEnvironment(id){if(id===env.id)return;const next=environments.find(e=>e.id===id);if(!next)throw Error('环境不存在');if(dirty)await saveCurrent();env=next;baseRevision=env.revision||0;selected.clear();primary='';undo=[];redo=[];await rebuild();viewGameCamera();recordRecent(id);status('已打开 '+env.name);}
function closeDialog(){$('#dialog-root').innerHTML='';}function dialog(title,body){$('#dialog-root').innerHTML=`<div class="dialog-shade"><section class="dialog" role="dialog" aria-modal="true" aria-label="${esc(title)}"><header><h2>${esc(title)}</h2>${btn('✕','close-dialog')}</header>${body}</section></div>`;$('#dialog-root button')?.focus();}
function openEnvironmentDialog(recent=false){const items=recent?recentIds().map(id=>environments.find(e=>e.id===id)).filter(Boolean):environments;dialog(recent?'最近打开的环境':'打开工程里的环境',`<p>这些环境都属于当前工程，随工程压缩包一起保存。</p><div class="picker-tools">${btn('全部环境','open-environment')}${btn('最近','recent-environments')}${btn('＋ 创建环境','new-environment')}</div><div class="environment-picker">${items.map(e=>`<button data-open-environment="${esc(e.id)}"><b>▣ ${esc(e.name)}</b><small>${e.nodes.length} 件物体${e.id===env.id?' · 当前打开':''}</small></button>`).join('')||'<p>还没有最近打开的环境。</p>'}</div>`);}
async function createEnvironmentNamed(name){if(!name.trim()||name.length>200)throw Error('名称请输入 1 至 200 个字');if(dirty)await saveCurrent();env=createEnvironment(name.trim());environments.push(env);baseRevision=-1;selected.clear();primary='';undo=[];redo=[];dirty=true;closeDialog();await rebuild();await saveCurrent();viewGameCamera();recordRecent(env.id);}
function boundsFor(all=false){const b=new THREE.Box3();for(const n of all?env.nodes.filter(n=>!['sky','light'].includes(n.kind)):roots())b.union(new THREE.Box3().setFromObject(runtime.objects.get(n.id)));return b.isEmpty()?new THREE.Box3(new THREE.Vector3(-1,0,-1),new THREE.Vector3(1,2,1)):b;}
function focus(b){const center=b.getCenter(new THREE.Vector3()),size=b.getSize(new THREE.Vector3()),distance=Math.max(3,size.length()/(2*Math.tan(THREE.MathUtils.degToRad(camera.fov/2))));const d=camera.position.clone().sub(orbit.target).normalize();camera.position.copy(center).addScaledVector(d.length()?d:new THREE.Vector3(0,.2,1).normalize(),distance);orbit.target.copy(center);orbit.update();}
async function addAsset(id,point){const a=assets.find(a=>a.id===id);if(!a||!['image','sceneModel'].includes(a.type))return;const n={...base(a.type==='image'?'imagePlane':'model',a.name),assetId:id};if(point)n.position=point.toArray();if(n.kind==='imagePlane'){const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('图片无法读取'));img.src=assetUrl(a);});n.width=8;n.height=8*img.height/img.width;n.position=point?.toArray()||[0,n.height/2,-6];n.unlit=true;n.alphaCutoff=0;}await mutate(()=>{env.nodes.push(n);selected=new Set([n.id]);primary=n.id;});}
async function perform(action){
 if(action==='close-dialog'){closeDialog();return;}if(action==='open-environment'){openEnvironmentDialog();return;}if(action==='recent-environments'){openEnvironmentDialog(true);return;}if(action==='new-environment'){const name=prompt('新环境名称','新环境 '+(environments.length+1));if(name!==null)await createEnvironmentNamed(name);return;}if(action==='save'){await saveCurrent();return;}
 if(action==='import-menu'){dialog('导入场景素材',`<p>导入的素材保存在当前工程里。</p><div class="picker-tools">${btn('导入 GLB 模型','import-model')}${btn('导入图片布景 / 全景图','import-image')}</div>`);return;}if(action==='import-model'||action==='import-image'){closeDialog();const imported=await send('import',{type:action==='import-image'?'image':'sceneModel'});for(const a of imported||[]){if(!assets.some(x=>x.id===a.id))assets.push(a);importedIds.add(a.id);}if(imported?.length){await mutate(()=>{for(const a of imported)library.assignments[a.id]=folder;});status('素材已导入，双击或拖入场景');}return;}
 if(action==='undo'&&undo.length){redo.push(state());restore(undo.pop());dirty=true;await rebuild();status('已撤销');return;}if(action==='redo'&&redo.length){undo.push(state());restore(redo.pop());dirty=true;await rebuild();status('已重做');return;}
 if(['translate','rotate','scale'].includes(action)){gizmo.setMode(action);status('拖动操作工具，或按 G / R / S 调整');return;}
 if(action==='copy'){clipboard=copySelection(env,[...selected]);status('已复制，按 Ctrl+V 粘贴');return;}if(action==='paste'||action==='duplicate'){const copied=action==='paste'?clipboard:copySelection(env,[...selected]);if(!copied.length)throw Error('先选择物体并复制');await mutate(()=>{selected=new Set(pasteSelection(env,copied));primary=[...selected].at(-1);});if(action==='duplicate')beginTransform('translate');return;}
 if(action==='delete'){if(!selected.size)return;await mutate(()=>{const ids=subtreeIds(env,[...selected]);env.nodes=env.nodes.filter(n=>!ids.has(n.id));selected.clear();primary='';});return;}if(action==='group'){await mutate(()=>{primary=groupSelection(env,[...selected]);selected=new Set([primary]);});return;}if(action==='ungroup'){await mutate(()=>{selected=new Set(ungroupSelection(env,[...selected]));primary=[...selected].at(-1)||'';});return;}
 if(['add-ground','add-light','add-sky'].includes(action)){await mutate(()=>{let n;if(action==='add-ground')n={...base('ground','地面'),position:[0,-.03,0],rotation:[-Math.PI/2,0,0],width:20,height:20,color:'#b7bfae'};else if(action==='add-light')n={...base('light','点光源'),position:[0,3,2],color:'#ffffff',intensity:30,distance:20,castShadow:false};else{if(env.nodes.some(n=>n.kind==='sky'))throw Error('已经有天空球，选中它就能更换图片');n={...base('sky','天空球'),color:env.background,assetId:''};}env.nodes.push(n);selected=new Set([n.id]);primary=n.id;});return;}
 if(action==='ground'){await mutate(()=>{for(const n of roots()){const o=runtime.objects.get(n.id),b=new THREE.Box3().setFromObject(o);if(!b.isEmpty()){const p=o.getWorldPosition(new THREE.Vector3());p.y-=b.min.y;n.position=o.parent.worldToLocal(p).toArray();}}});return;}
 if(action==='camera'){await mutate(()=>env.camera={position:camera.position.toArray(),target:orbit.target.toArray(),fov:camera.fov});status('游戏镜头已记录，记得保存');return;}if(action==='game-camera'){viewGameCamera();return;}if(action==='focus-people'){camera.up.set(0,1,0);camera.fov=32;camera.updateProjectionMatrix();camera.position.set(0,1.3,4.3);orbit.target.set(0,1.05,0);focus(new THREE.Box3().setFromObject(references));return;}if(action==='focus-selected'){focus(boundsFor());return;}if(action==='frame-all'){focus(boundsFor(true));return;}if(action==='box-select'){boxMode=true;orbit.enabled=false;status('左键拖动框选，Esc 取消');return;}
 if(action==='new-folder'){const name=prompt('文件夹名称');if(name===null)return;const text=name.trim();if(!text||/[\\/<>:"|?*]/.test(text)||['.','..'].includes(text))throw Error('请输入普通的文件夹名称');const path=folder?folder+'/'+text:text;if(library.folders.includes(path))throw Error('文件夹已经存在');await mutate(()=>library.folders.push(path));folder=path;renderAssets();return;}
 if(action==='help'){dialog('常用操作',`<div class="shortcut-list"><p>中键旋转　Shift＋中键平移　滚轮缩放</p><p>左键选择　Shift / Ctrl 多选　A 全选　Alt+A 取消全选　B 框选</p><p>G 移动　R 旋转　S 缩放；接着按 X / Y / Z 限定方向，可输入数字。Enter / 左键确认，Esc / 右键取消。</p><p>Ctrl+Z 撤销　Ctrl+Shift+Z 重做　Ctrl+C / V 复制 / 粘贴　Shift+D 复制后移动　X / Delete 删除</p><p>Ctrl+G 分组　Ctrl+Alt+G 拆组</p><p>小键盘 0 游戏镜头　1 / 3 / 7 前 / 右 / 顶视图　小键盘 . 聚焦所选　Home 全景</p><p>Ctrl+S 保存　Ctrl+O 打开工程内环境　Ctrl+N 新建环境</p><small>沿用 Blender 常用操作习惯；“分组”管理物品层级，不合并模型网格。</small></div>`);}
}
async function execute(action){if(busy||!env)return;if(modal){await finishTransform(false);return;}busy=true;try{await perform(action);}catch(error){status(error.message);}finally{busy=false;}}
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();function pointer(e){lastPointer.set(e.clientX,e.clientY);const r=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);}
function choose(id,e){if(e.shiftKey||e.ctrlKey){const ids=new Set(selected);ids.has(id)?ids.delete(id):ids.add(id);select([...ids]);}else select(id?[id]:[]);}
renderer.domElement.addEventListener('pointerdown',e=>{if(e.button!==0||busy)return;$('#viewport').focus({preventScroll:true});pointer(e);if(modal){finishTransform(true);return;}if(gizmo.axis)return;if(boxMode){boxStart={x:e.clientX,y:e.clientY,add:e.shiftKey||e.ctrlKey};$('#selection-box').hidden=false;return;}const hit=ray.intersectObjects(env.nodes.filter(n=>n.kind!=='sky').map(n=>runtime.objects.get(n.id)),true).find(h=>{for(let p=h.object;p;p=p.parent)if(!p.visible)return false;return true;});let o=hit?.object;while(o&&!o.userData.nodeId)o=o.parent;choose(o?.userData.nodeId||'',e);});
renderer.domElement.addEventListener('contextmenu',e=>{e.preventDefault();if(modal)finishTransform(false);});
document.addEventListener('pointermove',e=>{lastPointer.set(e.clientX,e.clientY);if(modal){try{updateModal(e);}catch(error){status(error.message);}return;}if(boxStart){const r=$('#viewport').getBoundingClientRect();Object.assign($('#selection-box').style,{left:Math.min(e.clientX,boxStart.x)-r.left+'px',top:Math.min(e.clientY,boxStart.y)-r.top+'px',width:Math.abs(e.clientX-boxStart.x)+'px',height:Math.abs(e.clientY-boxStart.y)+'px'});}});
document.addEventListener('pointerup',e=>{if(!boxStart)return;const r=renderer.domElement.getBoundingClientRect(),ids=boxStart.add?new Set(selected):new Set();for(const n of env.nodes.filter(n=>!['group','sky'].includes(n.kind))){const o=runtime.objects.get(n.id);if(!o.visible)continue;const b=new THREE.Box3().setFromObject(o),v=b.isEmpty()?o.getWorldPosition(new THREE.Vector3()):b.getCenter(new THREE.Vector3());v.project(camera);const x=r.left+(v.x+1)*r.width/2,y=r.top+(1-v.y)*r.height/2;if(v.z>=-1&&v.z<=1&&x>=Math.min(e.clientX,boxStart.x)&&x<=Math.max(e.clientX,boxStart.x)&&y>=Math.min(e.clientY,boxStart.y)&&y<=Math.max(e.clientY,boxStart.y))ids.add(n.id);}boxStart=null;boxMode=false;$('#selection-box').hidden=true;orbit.enabled=true;select([...ids]);});
document.addEventListener('dragstart',e=>{const c=e.target.closest('[data-asset-select]');if(c)e.dataTransfer.setData('text/plain',c.dataset.assetSelect);});renderer.domElement.addEventListener('dragover',e=>e.preventDefault());renderer.domElement.addEventListener('drop',async e=>{e.preventDefault();if(busy||modal)return;pointer(e);const p=ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),new THREE.Vector3());busy=true;try{await addAsset(e.dataTransfer.getData('text/plain'),p);}catch(error){status(error.message);}finally{busy=false;}});
document.addEventListener('dblclick',async e=>{const c=e.target.closest('[data-asset-select]');if(c&&!busy){busy=true;try{await addAsset(c.dataset.assetSelect);}catch(error){status(error.message);}finally{busy=false;}}});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||busy)return;try{if(b.dataset.openEnvironment){busy=true;try{await switchEnvironment(b.dataset.openEnvironment);closeDialog();}finally{busy=false;}return;}if(b.dataset.select){choose(b.dataset.select,e);return;}if(b.dataset.fold){collapsed.has(b.dataset.fold)?collapsed.delete(b.dataset.fold):collapsed.add(b.dataset.fold);renderPanels();return;}if(b.dataset.visible){await mutate(()=>{const n=env.nodes.find(n=>n.id===b.dataset.visible);n.visible=n.visible===false;});return;}if(b.hasAttribute('data-folder')){folder=b.dataset.folder;renderAssets();return;}if(b.dataset.assetSelect){if(!e.ctrlKey&&!e.shiftKey)assetSelection.clear();assetSelection.has(b.dataset.assetSelect)?assetSelection.delete(b.dataset.assetSelect):assetSelection.add(b.dataset.assetSelect);for(const card of document.querySelectorAll('[data-asset-select]'))card.classList.toggle('selected',assetSelection.has(card.dataset.assetSelect));return;}await execute(b.dataset.act);}catch(error){status(error.message);}});
document.addEventListener('change',async e=>{const t=e.target;if(t.id==='show-references'){references.visible=t.checked;return;}if(t.id==='show-grid'){grid.visible=t.checked;return;}if(t.id==='snap'){snap(t.checked);return;}if(busy||modal||gizmo.dragging||!env)return;busy=true;try{await mutate(()=>{const n=env.nodes.find(n=>n.id===primary);if(t.id==='asset-move'){for(const id of assetSelection)library.assignments[id]=t.value;}else if(t.dataset.env)env[t.dataset.env]=t.value;else if(t.dataset.light)env.lighting[t.dataset.light]=t.type==='number'?Number(t.value):t.value;else if(t.dataset.vector)n[t.dataset.vector][Number(t.dataset.index)]=Number(t.value)*(t.dataset.vector==='rotation'?Math.PI/180:1);else if(t.hasAttribute('data-alpha'))n.alphaCutoff=t.checked?.5:0;else if(t.dataset.node){if(t.dataset.node==='parentId')reparentNode(env,n.id,t.value||null);else n[t.dataset.node]=t.type==='checkbox'?t.checked:t.type==='number'?Number(t.value):t.value;}});}catch(error){status(error.message);}finally{busy=false;}});
function capture(){scene.updateMatrixWorld(true);return {before:state(),hadDirty:dirty,matrices:new Map(roots().map(n=>[n.id,runtime.objects.get(n.id).matrixWorld.clone()])),pivot:gizmo.object?.getWorldPosition(new THREE.Vector3())||new THREE.Vector3()};}
function applyDelta(s,delta){scene.updateMatrixWorld(true);const changes=[];for(const [id,m]of s.matrices){const n=env.nodes.find(n=>n.id===id),o=runtime.objects.get(id),copy=structuredClone(n);assignMatrix(copy,m.clone().premultiply(delta).premultiply(o.parent.matrixWorld.clone().invert()));changes.push({n,o,copy});}for(const {n,o,copy}of changes){Object.assign(n,{position:copy.position,rotation:copy.rotation,scale:copy.scale});o.position.fromArray(n.position);o.rotation.set(...n.rotation);o.scale.fromArray(n.scale);}dirty=true;}
gizmo.addEventListener('dragging-changed',e=>{orbit.enabled=!e.value;if(e.value){drag=capture();drag.pivotMatrix=gizmo.object.matrixWorld.clone();}else if(drag){checkpoint(drag.before);drag=null;attach();renderPanels();status('有未保存修改');}});
gizmo.addEventListener('objectChange',()=>{if(!drag)return;try{if(gizmo.object===pivot){pivot.updateMatrixWorld(true);applyDelta(drag,pivot.matrixWorld.clone().multiply(drag.pivotMatrix.clone().invert()));}else{const n=roots()[0],o=gizmo.object;if(n){n.position=o.position.toArray();n.rotation=[o.rotation.x,o.rotation.y,o.rotation.z];n.scale=o.scale.toArray().map(v=>Math.max(.01,v));o.scale.fromArray(n.scale);dirty=true;}}}catch(error){status(error.message);}});
function snap(on){gizmo.setTranslationSnap(on?.1:null);gizmo.setRotationSnap(on?Math.PI/12:null);gizmo.setScaleSnap(on?.1:null);}snap(true);
function beginTransform(mode){if(!roots().length){status('先选择物体');return;}gizmo.setMode(mode);const s=capture(),r=renderer.domElement.getBoundingClientRect(),v=s.pivot.clone().project(camera);s.screen=new THREE.Vector2(r.left+(v.x+1)*r.width/2,r.top+(1-v.y)*r.height/2);s.start=lastPointer.clone();if(s.start.x<r.left||s.start.x>r.right||s.start.y<r.top||s.start.y>r.bottom)s.start.copy(s.screen).add(new THREE.Vector2(80,0));s.mode=mode;s.axis='';s.number='';s.last=s.start.clone();s.plane=new THREE.Plane().setFromNormalAndCoplanarPoint(camera.getWorldDirection(new THREE.Vector3()),s.pivot);pointer({clientX:s.start.x,clientY:s.start.y});s.point=ray.ray.intersectPlane(s.plane,new THREE.Vector3())||s.pivot.clone();modal=s;orbit.enabled=false;gizmo.enabled=false;status('调整中：X / Y / Z 限定方向，可输入数字，Enter 确认，Esc 取消');}
function updateModal(e){const s=modal;if(!s)return;s.last.set(e.clientX,e.clientY);const axis=s.axis?new THREE.Vector3(s.axis==='x'?1:0,s.axis==='y'?1:0,s.axis==='z'?1:0):null,num=s.number!==''&&s.number!=='-'&&Number.isFinite(Number(s.number))?Number(s.number):null;let delta;
 if(s.mode==='translate'){pointer(e);const hit=ray.ray.intersectPlane(s.plane,new THREE.Vector3())||s.point,move=hit.clone().sub(s.point);if(axis){const nearView=Math.abs(axis.dot(camera.getWorldDirection(new THREE.Vector3())))>.95;const amount=nearView?(s.start.y-s.last.y)*2*camera.position.distanceTo(s.pivot)*Math.tan(THREE.MathUtils.degToRad(camera.fov/2))/renderer.domElement.getBoundingClientRect().height:move.dot(axis);move.copy(axis.clone().multiplyScalar(num??amount));}else if(num!==null)move.set(num,0,0);if($('#snap').checked&&num===null)move.toArray().forEach((v,i)=>move.setComponent(i,Math.round(v*10)/10));delta=new THREE.Matrix4().makeTranslation(...move.toArray());}
 else{let m;if(s.mode==='rotate'){let a=num!==null?THREE.MathUtils.degToRad(num):Math.atan2(s.last.y-s.screen.y,s.last.x-s.screen.x)-Math.atan2(s.start.y-s.screen.y,s.start.x-s.screen.x);if($('#snap').checked&&num===null)a=Math.round(a/(Math.PI/12))*Math.PI/12;m=new THREE.Matrix4().makeRotationAxis(axis||camera.getWorldDirection(new THREE.Vector3()),num!==null?a:-a);}else{let f=num??Math.max(.01,s.last.distanceTo(s.screen)/Math.max(20,s.start.distanceTo(s.screen)));if($('#snap').checked&&num===null)f=Math.max(.1,Math.round(f*10)/10);if(f<=0)throw Error('大小请输入大于零的数');m=new THREE.Matrix4().makeScale(axis?(axis.x?f:1):f,axis?(axis.y?f:1):f,axis?(axis.z?f:1):f);}delta=new THREE.Matrix4().makeTranslation(...s.pivot.toArray()).multiply(m).multiply(new THREE.Matrix4().makeTranslation(...s.pivot.clone().negate().toArray()));}applyDelta(s,delta);status(`${{translate:'移动',rotate:'旋转',scale:'缩放'}[s.mode]} ${s.axis.toUpperCase()} ${s.number} · Enter 确认 / Esc 取消`);
}
async function finishTransform(confirm){if(!modal)return;const s=modal;modal=null;orbit.enabled=true;gizmo.enabled=true;if(confirm)checkpoint(s.before);else {restore(s.before);dirty=s.hadDirty;}await rebuild();status(confirm?'调整已确认':'已取消调整');}
document.addEventListener('keydown',async e=>{if(e.target.matches('input,select,textarea,[contenteditable=true]'))return;if(e.key==='Escape'){e.preventDefault();if(modal)await finishTransform(false);else{boxMode=false;boxStart=null;$('#selection-box').hidden=true;orbit.enabled=true;closeDialog();}return;}if(busy||gizmo.dragging)return;if(modal){e.preventDefault();if(e.key==='Enter'){await finishTransform(true);return;}if(['x','y','z'].includes(e.key.toLowerCase())){modal.axis=e.key.toLowerCase();modal.number='';}else if(/[0-9.\-]/.test(e.key)&&e.key.length===1)modal.number+=e.key;else if(e.key==='Backspace')modal.number=modal.number.slice(0,-1);try{updateModal({clientX:modal.last.x,clientY:modal.last.y});}catch(error){status(error.message);}return;}if($('#dialog-root').children.length)return;const key=e.key.toLowerCase(),ctrl=e.ctrlKey||e.metaKey;let action='';if(ctrl)action={s:'save',o:'open-environment',n:'new-environment',z:e.shiftKey?'redo':'undo',y:'redo',c:'copy',v:'paste',g:e.altKey?'ungroup':'group'}[key]||'';else if(e.shiftKey&&key==='d')action='duplicate';else if(['g','r','s'].includes(key)){e.preventDefault();beginTransform({g:'translate',r:'rotate',s:'scale'}[key]);return;}else if(key==='a'){e.preventDefault();select(e.altKey?[]:env.nodes.map(n=>n.id));return;}else action={b:'box-select',x:'delete',delete:'delete',home:'frame-all'}[key]||'';if(e.code==='Numpad0')action='game-camera';if(e.code==='NumpadDecimal')action='focus-selected';if(['Numpad1','Numpad3','Numpad7'].includes(e.code)){e.preventDefault();const d=Math.max(4,camera.position.distanceTo(orbit.target));camera.up.set(0,e.code==='Numpad7'?0:1,e.code==='Numpad7'?-1:0);camera.position.copy(orbit.target).add(e.code==='Numpad1'?new THREE.Vector3(0,0,d):e.code==='Numpad3'?new THREE.Vector3(d,0,0):new THREE.Vector3(0,d,0));orbit.update();return;}if(action){e.preventDefault();await execute(action);}});
new ResizeObserver(()=>{const r=$('#viewport').getBoundingClientRect(),w=Math.min(r.width,r.height*16/9);if(w>0){renderer.setSize(w,w*9/16,false);camera.aspect=16/9;camera.updateProjectionMatrix();}}).observe($('#viewport'));
renderer.setAnimationLoop(()=>{if(document.hidden)return;orbit.update();runtime.update(camera);for(const h of lightHelpers)h.update();renderer.render(scene,camera);});window.environmentHasChanges=()=>dirty;window.environmentReady=()=>Boolean(env&&!busy);
if(new URLSearchParams(location.search).has('smoke'))window.environmentSmoke=async()=>{env.name='窗口保存验证';env.camera.position=[0,2,8];env.camera.target=[0,1,0];const group=base('group','测试分组');env.nodes.push(group);await addAsset(assets.find(a=>a.type==='image').id);const board=env.nodes.at(-1);board.position=[0,2,-6];board.parentId=group.id;const model=assets.find(a=>a.type==='sceneModel');await addAsset(model.id);const box=env.nodes.at(-1);box.position=[-1,0,0];box.scale=[.4,.4,.4];await rebuild();const count=env.nodes.length;select([board.id,box.id]);await perform('copy');await perform('paste');if(selected.size!==2)throw Error('多选复制粘贴失败');await perform('group');if(env.nodes.find(n=>n.id===primary).kind!=='group')throw Error('分组失败');await perform('ungroup');if(selected.size!==2)throw Error('拆组失败');await perform('undo');await perform('redo');await perform('delete');if(env.nodes.length!==count)throw Error('撤销或删除失败');await perform('add-light');await perform('add-sky');await mutate(()=>{library.folders.push('测试素材');library.assignments[model.id]='测试素材';});select([box.id]);const oldX=env.nodes.find(n=>n.id===box.id).position[0];$('#viewport').focus();for(const key of ['g','x','2','Enter'])$('#viewport').dispatchEvent(new KeyboardEvent('keydown',{key,bubbles:true}));for(let attempt=0;attempt<100&&(modal||busy);attempt++)await new Promise(resolve=>setTimeout(resolve,20));await new Promise(resolve=>setTimeout(resolve,100));if(Math.abs(env.nodes.find(n=>n.id===box.id).position[0]-oldX-2)>.001)throw Error('G X 数字移动失败');await perform('undo');viewGameCamera();await saveCurrent();let rejected=false;try{await send('commit',{environment:env,environmentLibrary:library,assets,projectId,baseRevision:0});}catch(error){rejected=/版本|改变/.test(error.message);}if(!rejected)throw Error('旧版本提交未被阻止');const first=env.id;await createEnvironmentNamed('第二个环境验证');await switchEnvironment(first);openEnvironmentDialog();const listed=document.querySelectorAll('[data-open-environment]').length;closeDialog();select([]);viewGameCamera();if(listed<2||references.children.length!==3)throw Error('环境选择或参考人物失败');return {ok:true,layout:'viewport-library-outliner',environmentPickerCount:listed,environmentCount:environments.length,referencePeople:3,gameAspect:camera.aspect,multiSelectClipboard:true,groupUngroup:true,keyboardTransform:true,libraryFolderSaved:true,lightAndSky:true,nodeCount:env.nodes.length,objects:runtime.objects.size,revision:baseRevision,staleRevisionRejected:true,switchSaved:true};};
window.addEventListener('beforeunload',()=>{renderer.setAnimationLoop(null);runtime.clear();gizmo.dispose();orbit.dispose();renderer.dispose();});
try{const init=await send('init');env=init.environment;environments=(init.environments||[env]).map(e=>e.id===env.id?env:e);assets=init.assets;library=init.environmentLibrary||{folders:[],assignments:{}};projectId=init.projectId;baseRevision=env.revision||0;referenceSettings=init.referenceSettings||{};referenceMultiple=Boolean(init.referenceMultiple);addReferencePeople(references,referenceSettings,referenceMultiple);await rebuild();viewGameCamera();recordRecent(env.id);status('可以开始搭建');}catch(error){status(error.message);}

if(new URLSearchParams(location.search).has('smoke')){window.environmentOpenPicker=()=>openEnvironmentDialog();window.environmentClosePicker=closeDialog;}
